// البيانات الأولية الافتراضية لنظام مفاضلة جامعة صنعاء
const DEFAULT_USERS = [
  { id: 1, username: 'admin', password: 'admin123', name: 'د. رئيس لجنة المفاضلة', role: 'super_admin', title: 'المدير الأعلى / رئيس اللجنة' },
  { id: 2, username: 'entry', password: 'entry123', name: 'أحمد الإداري', role: 'data_entry', title: 'مُدخل بيانات' },
  { id: 3, username: 'viewer', password: 'viewer123', name: 'د. المراجع القانوني', role: 'auditor', title: 'مراجع مطلع' }
];

const DEFAULT_SETTINGS = {
  masterGrantsCount: 3,
  phdGrantsCount: 3,
  referenceYear: 2026,
  universityName: 'جامعة صنعاء',
  councilName: 'مجلس الجامعة - لجنة المفاضلة والتنافس',
  rectorName: 'أ.د. القاسم محمد عباس',
  competitionLocation: 'مقر الأمانة العامة / قاعة اجتماعات مجلس الجامعة الرئيسي - جامعة صنعاء',
  competitionDate: 'الخميس، 30 يوليو 2026م (الساعة 10:00 صباحاً)',
  applicationTitle: 'نظام المفاضلة والتنافس الإلكتروني لمنتسبي الكادر الإداري لجامعة صنعاء (ماجستير ودكتوراه)',
  supabaseUrl: 'https://wpnujibmxrxxaqriadez.supabase.co',
  supabaseKey: 'sb_publishable_PudkaqYYnpEc8JrQfNUyCw_BWSzZElC'
};

const DEFAULT_COMMITTEE_MEMBERS = [
  { id: 1, name: 'أ.د. ابراهيم المطاع', adminTitle: 'نائب رئيس الجامعة للشؤون الأكاديمية', committeeRole: 'رئيس اللجنة' },
  { id: 2, name: 'د. حمود الأهنومي', adminTitle: 'نائب رئيس الجامعة للدراسات العليا', committeeRole: 'عضواً' },
  { id: 3, name: 'أ. اسكندر المقالح', adminTitle: 'أمين عام الجامعة', committeeRole: 'عضواً' },
  { id: 4, name: 'د. محمد نجاد', adminTitle: 'عميد كلية الشريعة والقانون', committeeRole: 'عضواً' },
  { id: 5, name: 'د. هاني مغلس', adminTitle: 'عميد كلية التجارة والاقتصاد', committeeRole: 'عضواً' }
];

const DEFAULT_CRITERIA = {
  specialization: {
    enabled: true,
    weightName: 'الاحتياج للتخصص',
    maxPoints: 25,
    items: [
      { name: 'شريعة وقانون', points: 25 },
      { name: 'علوم حاسوب', points: 25 },
      { name: 'اقتصاد ومحاسبة', points: 20 },
      { name: 'إدارة عامة', points: 20 },
      { name: 'إدارة أعمال', points: 18 },
      { name: 'أخرى', points: 10 }
    ]
  },
  seniority: {
    enabled: true,
    weightName: 'تاريخ التعيين (الأقدمية)',
    maxPoints: 30,
    startYear: 1990,
    endYear: 2030,
    stepYears: 1, // كل سنة أو سنتين أو 5 سنوات
    brackets: [
      { label: '1990 - 1994م', minYear: 1990, maxYear: 1994, points: 30 },
      { label: '1995 - 2000م', minYear: 1995, maxYear: 2000, points: 25 },
      { label: '2001 - 2005م', minYear: 2001, maxYear: 2005, points: 20 },
      { label: '2006 - 2010م', minYear: 2006, maxYear: 2010, points: 15 },
      { label: '2011 - 2015م', minYear: 2011, maxYear: 2015, points: 10 },
      { label: '2016 - 2020م', minYear: 2016, maxYear: 2020, points: 5 },
      { label: '2021 - 2030م', minYear: 2021, maxYear: 2030, points: 2 }
    ]
  },
  age: {
    enabled: true,
    weightName: 'الفئة العمرية (العمر)',
    maxPoints: 25,
    minAge: 25,
    maxAge: 56,
    stepYears: 5, // مرونة الفئات 1، 2، أو 5 سنوات
    brackets: [
      { label: '50 - 56 سنة', minAge: 50, maxAge: 120, points: 25 },
      { label: '45 - 49 سنة', minAge: 45, maxAge: 49, points: 20 },
      { label: '40 - 44 سنة', minAge: 40, maxAge: 44, points: 15 },
      { label: '35 - 39 سنة', minAge: 35, maxAge: 39, points: 10 },
      { label: '30 - 34 سنة', minAge: 30, maxAge: 34, points: 5 },
      { label: '25 - 29 سنة', minAge: 0, maxAge: 29, points: 2 }
    ]
  },
  grade: {
    enabled: true,
    weightName: 'تقدير المؤهل (البكالوريوس/المؤهل)',
    maxPoints: 20,
    items: [
      { name: 'ممتاز', points: 20 },
      { name: 'جيد جداً', points: 15 },
      { name: 'جيد', points: 10 },
      { name: 'مقبول', points: 5 }
    ]
  },
  customCriteria: [
    { id: 'c1', name: 'تقييم الأداء السنوي', maxPoints: 10, enabled: true },
    { id: 'c2', name: 'الأبحاث والإنتاج العلمي', maxPoints: 5, enabled: false }
  ]
};

const PRESEEDED_CANDIDATES = [
  {
    "id": 1,
    "name": "معمر علي مصلح المقالح",
    "degree": "دكتوراه",
    "hiring_service": "ـــــــــــــــــ",
    "hiring_univ": "1994-01-24",
    "specialization": "إدارة تنمية محلية",
    "grad_year": "2013",
    "grade": "جيد",
    "birth_date": "1972",
    "source_sheet": "دكتوراه"
  },
  {
    "id": 2,
    "name": "فايز عباد أحمد الخولاني",
    "degree": "دكتوراه",
    "hiring_service": "ـــــــــــــــــ",
    "hiring_univ": "1994-09-19",
    "specialization": "إدارة عامة",
    "grad_year": "2025",
    "grade": "جيد",
    "birth_date": "1975",
    "source_sheet": "دكتوراه"
  },
  {
    "id": 3,
    "name": "حمود أحمد أحمد السياغي",
    "degree": "دكتوراه",
    "hiring_service": "ـــــــــــــــــ",
    "hiring_univ": "1995-12-27",
    "specialization": "إدارة عامة",
    "grad_year": "2023",
    "grade": "جيد",
    "birth_date": "1974",
    "source_sheet": "دكتوراه"
  },
  {
    "id": 4,
    "name": "منذر عبدالله نعمان الحكيمي",
    "degree": "دكتوراه",
    "hiring_service": "ـــــــــــــــــ",
    "hiring_univ": "1996-08-25",
    "specialization": "كيمياء",
    "grad_year": "2025",
    "grade": "جيد",
    "birth_date": "1970",
    "source_sheet": "دكتوراه"
  },
  {
    "id": 5,
    "name": "محمد حمود عبد الرب كرش",
    "degree": "دكتوراه",
    "hiring_service": "1991-01-10",
    "hiring_univ": "2000-08-13",
    "specialization": "شريعة وقانون",
    "grad_year": "2023",
    "grade": "جيد جداً",
    "birth_date": "1980",
    "source_sheet": "دكتوراه"
  },
  {
    "id": 6,
    "name": "قائد صالح سعد المنامه",
    "degree": "دكتوراه",
    "hiring_service": "ـــــــــــــــــ",
    "hiring_univ": "2000-09-20",
    "specialization": "إدارة عامة",
    "grad_year": "2016",
    "grade": "جيد جداً",
    "birth_date": "1974",
    "source_sheet": "دكتوراه"
  },
  {
    "id": 7,
    "name": "فتحية محمد حسين سريع",
    "degree": "دكتوراه",
    "hiring_service": "ـــــــــــــــــ",
    "hiring_univ": "2001-07-22",
    "specialization": "إدارة عامة",
    "grad_year": "2017",
    "grade": "جيد",
    "birth_date": "1983",
    "source_sheet": "دكتوراه"
  },
  {
    "id": 8,
    "name": "بشرى أحمد إسماعيل الاكوع",
    "degree": "دكتوراه",
    "hiring_service": "ـــــــــــــــــ",
    "hiring_univ": "2001-10-30",
    "specialization": "أحياء دقيقة طبية",
    "grad_year": "2012",
    "grade": "جيد",
    "birth_date": "1977",
    "source_sheet": "دكتوراه"
  },
  {
    "id": 9,
    "name": "عمار محمد أحمد مسعد العيوي",
    "degree": "دكتوراه",
    "hiring_service": "ـــــــــــــــــ",
    "hiring_univ": "2002-07-31",
    "specialization": "علم اجتماع السكان",
    "grad_year": "2020",
    "grade": "جيد",
    "birth_date": "1980",
    "source_sheet": "دكتوراه"
  },
  {
    "id": 10,
    "name": "محمد يحيى علي المندي",
    "degree": "دكتوراه",
    "hiring_service": "ـــــــــــــــــ",
    "hiring_univ": "2003-06-14",
    "specialization": "إدارة اعمال",
    "grad_year": "2017",
    "grade": "جيد",
    "birth_date": "1977",
    "source_sheet": "دكتوراه"
  },
  {
    "id": 11,
    "name": "منى عبدالحفيظ الانسي",
    "degree": "دكتوراه",
    "hiring_service": "ـــــــــــــــــ",
    "hiring_univ": "2003-07-07",
    "specialization": "إدارة أعمال",
    "grad_year": "2025",
    "grade": "ممتاز",
    "birth_date": "1979",
    "source_sheet": "دكتوراه"
  },
  {
    "id": 12,
    "name": "عبدالعزيز حزام سعد السامعي",
    "degree": "دكتوراه",
    "hiring_service": "ـــــــــــــــــ",
    "hiring_univ": "2007-12-09",
    "specialization": "ادارة عامة",
    "grad_year": "2019",
    "grade": "جيد",
    "birth_date": "1976",
    "source_sheet": "دكتوراه"
  },
  {
    "id": 13,
    "name": "محمد نعمان أحمد البريهي",
    "degree": "دكتوراه",
    "hiring_service": "ـــــــــــــــــ",
    "hiring_univ": "2007-12-31",
    "specialization": "إدارة عامة",
    "grad_year": "2019",
    "grade": "جيد",
    "birth_date": "1977",
    "source_sheet": "دكتوراه"
  },
  {
    "id": 14,
    "name": "عبد الرحمن حسن النجار",
    "degree": "دكتوراه",
    "hiring_service": "ـــــــــــــــــ",
    "hiring_univ": "2008-09-10",
    "specialization": "إدارة عامة",
    "grad_year": "2025",
    "grade": "جيد",
    "birth_date": "1979",
    "source_sheet": "دكتوراه"
  },
  {
    "id": 15,
    "name": "هزاع علي ناصر الحراسي",
    "degree": "دكتوراه",
    "hiring_service": "ـــــــــــــــــ",
    "hiring_univ": "2008-09-10",
    "specialization": "إدارة عامة",
    "grad_year": "2019",
    "grade": "جيد جداً",
    "birth_date": "1978",
    "source_sheet": "دكتوراه"
  },
  {
    "id": 16,
    "name": "محمد حزام يحيى الشامي",
    "degree": "دكتوراه",
    "hiring_service": "1994-11-16",
    "hiring_univ": "2010-02-28",
    "specialization": "جغرافيا سياحية",
    "grad_year": "2018",
    "grade": "جيد جداً",
    "birth_date": "1976",
    "source_sheet": "دكتوراه"
  },
  {
    "id": 17,
    "name": "فؤاد منصور أحمد الورد",
    "degree": "دكتوراه",
    "hiring_service": "ـــــــــــــــــ",
    "hiring_univ": "2010-10-13",
    "specialization": "ترجمة لغة أنجليزية",
    "grad_year": "2020",
    "grade": "جيد",
    "birth_date": "1982",
    "source_sheet": "دكتوراه"
  },
  {
    "id": 18,
    "name": "نورالدين مصلح علي الفرزعي",
    "degree": "دكتوراه",
    "hiring_service": "ـــــــــــــــــ",
    "hiring_univ": "2010-10-13",
    "specialization": "إدارة عامة",
    "grad_year": "2026",
    "grade": "جيد",
    "birth_date": "1981",
    "source_sheet": "دكتوراه"
  },
  {
    "id": 19,
    "name": "ماجد سعيد سعيد علي",
    "degree": "دكتوراه",
    "hiring_service": "2012-01-01",
    "hiring_univ": "2013-02-10",
    "specialization": "شبكات",
    "grad_year": "2022",
    "grade": "جيد جداً",
    "birth_date": "1980",
    "source_sheet": "دكتوراه"
  },
  {
    "id": 20,
    "name": "إنتصار عبدالجليل غالب",
    "degree": "دكتوراه",
    "hiring_service": "2012-01-01",
    "hiring_univ": "2013-02-18",
    "specialization": "نشر الكتاب",
    "grad_year": "2012",
    "grade": "جيد",
    "birth_date": "1972",
    "source_sheet": "دكتوراه"
  },
  {
    "id": 21,
    "name": "أمجد إسماعيل محمد عبدالمغني",
    "degree": "دكتوراه",
    "hiring_service": "2012-01-01",
    "hiring_univ": "2013-02-18",
    "specialization": "ترميم وصيانة اثار",
    "grad_year": "2021",
    "grade": "ممتاز",
    "birth_date": "1979",
    "source_sheet": "دكتوراه"
  },
  {
    "id": 22,
    "name": "خلود عبدالعزيز الشوافي",
    "degree": "دكتوراه",
    "hiring_service": "2012-01-01",
    "hiring_univ": "2013-02-18",
    "specialization": "فيزياء -بلازماء",
    "grad_year": "2024",
    "grade": "جيد",
    "birth_date": "1982",
    "source_sheet": "دكتوراه"
  },
  {
    "id": 23,
    "name": "كفى سالم حيدر محمد",
    "degree": "دكتوراه",
    "hiring_service": "2012-01-01",
    "hiring_univ": "2013-02-18",
    "specialization": "إقتصاد",
    "grad_year": "2026",
    "grade": "جيد",
    "birth_date": "1972",
    "source_sheet": "دكتوراه"
  },
  {
    "id": 24,
    "name": "لطيفة حمود علي المرسي",
    "degree": "دكتوراه",
    "hiring_service": "2012-01-01",
    "hiring_univ": "2013-02-18",
    "specialization": "مناهج العلوم وطرق تدريسها",
    "grad_year": "2017",
    "grade": "جيد",
    "birth_date": "1979",
    "source_sheet": "دكتوراه"
  },
  {
    "id": 25,
    "name": "ندى عصام قايد عبدالحق الاغبري",
    "degree": "دكتوراه",
    "hiring_service": "2012-01-01",
    "hiring_univ": "2013-02-18",
    "specialization": "الدراسات السكانية",
    "grad_year": "2025",
    "grade": "ــــــــــــ",
    "birth_date": "1983",
    "source_sheet": "دكتوراه"
  },
  {
    "id": 26,
    "name": "وجيدة إبراهيم علي محمد الاغبري",
    "degree": "دكتوراه",
    "hiring_service": "2012-01-01",
    "hiring_univ": "2013-06-29",
    "specialization": "مناهج العلوم",
    "grad_year": "2025",
    "grade": "ممتاز",
    "birth_date": "1979",
    "source_sheet": "دكتوراه"
  },
  {
    "id": 27,
    "name": "نوال أحمد أحمد العرشي",
    "degree": "دكتوراه",
    "hiring_service": "2013-11-13",
    "hiring_univ": "2013-07-28",
    "specialization": "أثار قديمة",
    "grad_year": "2010",
    "grade": "جيد",
    "birth_date": "1977",
    "source_sheet": "دكتوراه"
  },
  {
    "id": 28,
    "name": "زينب علي محمد الانسي",
    "degree": "دكتوراه",
    "hiring_service": "ـــــــــــــــــ",
    "hiring_univ": "2013-12-05",
    "specialization": "كيمياء عضوية",
    "grad_year": "2023",
    "grade": "جيد",
    "birth_date": "1981",
    "source_sheet": "دكتوراه"
  },
  {
    "id": 29,
    "name": "إبراهيم عبدالله إسحاق",
    "degree": "دكتوراه",
    "hiring_service": "ـــــــــــــــــ",
    "hiring_univ": "2014-11-26",
    "specialization": "إدارة عامة",
    "grad_year": "2023",
    "grade": "جيد",
    "birth_date": "1984",
    "source_sheet": "دكتوراه"
  },
  {
    "id": 30,
    "name": "امة الخالق عبدالرحمن المهدي",
    "degree": "دكتوراه",
    "hiring_service": "ـــــــــــــــــ",
    "hiring_univ": "2015-09-16",
    "specialization": "تفسير وعلوم القراءان",
    "grad_year": "2025",
    "grade": "جيد جداً",
    "birth_date": "1978",
    "source_sheet": "دكتوراه"
  },
  {
    "id": 31,
    "name": "خالد محمد سالم عوض عفيف",
    "degree": "ماجستير",
    "hiring_service": "ـــــــــــــــــ",
    "hiring_univ": "1992-07-19",
    "specialization": "مكتبات وعلم المعلومات",
    "grad_year": "2026",
    "grade": "مقبول",
    "birth_date": "1980",
    "source_sheet": "مــاجستيـر"
  },
  {
    "id": 32,
    "name": "خالد عبده فرحان علي",
    "degree": "ماجستير",
    "hiring_service": "ـــــــــــــــــ",
    "hiring_univ": "1995-10-05",
    "specialization": "محاسبة",
    "grad_year": "2002",
    "grade": "مقبول",
    "birth_date": "1975",
    "source_sheet": "مــاجستيـر"
  },
  {
    "id": 33,
    "name": "حسن عمر مجلي",
    "degree": "ماجستير",
    "hiring_service": "ـــــــــــــــــ",
    "hiring_univ": "1997-09-25",
    "specialization": "علوم بحار",
    "grad_year": "1996",
    "grade": "مقبول",
    "birth_date": "1972",
    "source_sheet": "مــاجستيـر"
  },
  {
    "id": 34,
    "name": "مرتضى عبدالوارث محمد مجاهد",
    "degree": "ماجستير",
    "hiring_service": "ـــــــــــــــــ",
    "hiring_univ": "2002-09-21",
    "specialization": "بحوث اجتماعية وسكانية",
    "grad_year": "2007",
    "grade": "جيد",
    "birth_date": "1974",
    "source_sheet": "مــاجستيـر"
  },
  {
    "id": 35,
    "name": "خالد حسين احسن المحمدي",
    "degree": "ماجستير",
    "hiring_service": "ـــــــــــــــــ",
    "hiring_univ": "2002-09-21",
    "specialization": "جغرافيا فلرعي تاريخ",
    "grad_year": "2001",
    "grade": "جيد",
    "birth_date": "1978",
    "source_sheet": "مــاجستيـر"
  },
  {
    "id": 36,
    "name": "امة الرزاق عبدالله زيد أبو طالب",
    "degree": "ماجستير",
    "hiring_service": "ـــــــــــــــــ",
    "hiring_univ": "2003-06-14",
    "specialization": "شريعة وقانون",
    "grad_year": "2019",
    "grade": "جيد",
    "birth_date": "1990",
    "source_sheet": "مــاجستيـر"
  },
  {
    "id": 37,
    "name": "أحمد صالح الربوعي",
    "degree": "ماجستير",
    "hiring_service": "ـــــــــــــــــ",
    "hiring_univ": "2004-08-08",
    "specialization": "شريعة وقانون",
    "grad_year": "2017",
    "grade": "مقبول",
    "birth_date": "1979",
    "source_sheet": "مــاجستيـر"
  },
  {
    "id": 38,
    "name": "يحيى محمد صالح الصديعي",
    "degree": "ماجستير",
    "hiring_service": "ـــــــــــــــــ",
    "hiring_univ": "2005-11-28",
    "specialization": "علوم الأرض والبيئة طبقات ونفط",
    "grad_year": "2005",
    "grade": "جيد",
    "birth_date": "1979",
    "source_sheet": "مــاجستيـر"
  },
  {
    "id": 39,
    "name": "إبراهيم أحمد هاشم الشهاري",
    "degree": "ماجستير",
    "hiring_service": "ـــــــــــــــــ",
    "hiring_univ": "2007-12-09",
    "specialization": "صيدلة",
    "grad_year": "2010",
    "grade": "جيد",
    "birth_date": "1975",
    "source_sheet": "مــاجستيـر"
  },
  {
    "id": 40,
    "name": "نوال حسن محمد باري",
    "degree": "ماجستير",
    "hiring_service": "ـــــــــــــــــ",
    "hiring_univ": "2008-09-10",
    "specialization": "تكنولوجيا التعليم",
    "grad_year": "2021",
    "grade": "ممتاز",
    "birth_date": "1979",
    "source_sheet": "مــاجستيـر"
  },
  {
    "id": 41,
    "name": "صالح حميد حميد العنمي",
    "degree": "ماجستير",
    "hiring_service": "2004-12-01",
    "hiring_univ": "2009-12-12",
    "specialization": "فيزياء",
    "grad_year": "2003",
    "grade": "جيد",
    "birth_date": "1980",
    "source_sheet": "مــاجستيـر"
  },
  {
    "id": 42,
    "name": "صادق محسن عقيل الغابري",
    "degree": "ماجستير",
    "hiring_service": "ـــــــــــــــــ",
    "hiring_univ": "2010-10-13",
    "specialization": "إذاعة وتلفزيون",
    "grad_year": "2010",
    "grade": "جيد جداً",
    "birth_date": "1980",
    "source_sheet": "مــاجستيـر"
  },
  {
    "id": 43,
    "name": "أسماء محمد ناصر عوضه",
    "degree": "ماجستير",
    "hiring_service": "ـــــــــــــــــ",
    "hiring_univ": "2010-12-14",
    "specialization": "علوم حياة",
    "grad_year": "2008",
    "grade": "ممتاز",
    "birth_date": "1984",
    "source_sheet": "مــاجستيـر"
  },
  {
    "id": 44,
    "name": "سميحة عبدالله شرف عبدالخالق",
    "degree": "ماجستير",
    "hiring_service": "ـــــــــــــــــ",
    "hiring_univ": "2010-12-14",
    "specialization": "تاريخ فرعي جغرافيا",
    "grad_year": "2008",
    "grade": "جيد جداً",
    "birth_date": "1983",
    "source_sheet": "مــاجستيـر"
  },
  {
    "id": 45,
    "name": "محمد عبدالرحمن دماج",
    "degree": "ماجستير",
    "hiring_service": "ـــــــــــــــــ",
    "hiring_univ": "2011-02-05",
    "specialization": "علوم سياسية",
    "grad_year": "2008",
    "grade": "جيد جداً",
    "birth_date": "1985",
    "source_sheet": "مــاجستيـر"
  },
  {
    "id": 46,
    "name": "أمة العليم حسين أحمد نواس",
    "degree": "ماجستير",
    "hiring_service": "ـــــــــــــــــ",
    "hiring_univ": "2011-07-02",
    "specialization": "لغة عربية",
    "grad_year": "2009",
    "grade": "جيد",
    "birth_date": "1980",
    "source_sheet": "مــاجستيـر"
  },
  {
    "id": 47,
    "name": "محمد محمد علي نجاد",
    "degree": "ماجستير",
    "hiring_service": "ـــــــــــــــــ",
    "hiring_univ": "2011-08-02",
    "specialization": "شريعة وقانون",
    "grad_year": "2025",
    "grade": "جيد جداً",
    "birth_date": "1982",
    "source_sheet": "مــاجستيـر"
  },
  {
    "id": 48,
    "name": "بلقيس طه عبدالله المقطري",
    "degree": "ماجستير",
    "hiring_service": "ـــــــــــــــــ",
    "hiring_univ": "2011-08-02",
    "specialization": "مكتبات وعلم المعلومات",
    "grad_year": "2015",
    "grade": "مفبول",
    "birth_date": "1981",
    "source_sheet": "مــاجستيـر"
  },
  {
    "id": 49,
    "name": "يحيى علي حزام المساجدي",
    "degree": "ماجستير",
    "hiring_service": "ـــــــــــــــــ",
    "hiring_univ": "2011-08-02",
    "specialization": "معلم حاسوب",
    "grad_year": "2024",
    "grade": "جيد",
    "birth_date": "1984",
    "source_sheet": "مــاجستيـر"
  },
  {
    "id": 50,
    "name": "مريم محمود ناشر السريحي",
    "degree": "ماجستير",
    "hiring_service": "ـــــــــــــــــ",
    "hiring_univ": "2011-08-27",
    "specialization": "كيمياء",
    "grad_year": "2009",
    "grade": "مقبول",
    "birth_date": "1983",
    "source_sheet": "مــاجستيـر"
  },
  {
    "id": 51,
    "name": "وداد إسماعيل علي الشميري",
    "degree": "ماجستير",
    "hiring_service": "ـــــــــــــــــ",
    "hiring_univ": "2011-12-21",
    "specialization": "دبلوم تقني",
    "grad_year": "2016",
    "grade": "ممتاز",
    "birth_date": "1980",
    "source_sheet": "مــاجستيـر"
  },
  {
    "id": 52,
    "name": "محمد حسن أحمد العنسي",
    "degree": "ماجستير",
    "hiring_service": "ـــــــــــــــــ",
    "hiring_univ": "2012-08-14",
    "specialization": "دراسات انجليزية",
    "grad_year": "2010",
    "grade": "جيد",
    "birth_date": "1986",
    "source_sheet": "مــاجستيـر"
  },
  {
    "id": 53,
    "name": "هاني يحيى حسين الحرفي",
    "degree": "ماجستير",
    "hiring_service": "ـــــــــــــــــ",
    "hiring_univ": "2012-11-18",
    "specialization": "علوم سياسية",
    "grad_year": "2002",
    "grade": "جيد",
    "birth_date": "1979",
    "source_sheet": "مــاجستيـر"
  },
  {
    "id": 54,
    "name": "محسن علي أحمد المحبشي",
    "degree": "ماجستير",
    "hiring_service": "ـــــــــــــــــ",
    "hiring_univ": "2013-02-10",
    "specialization": "بساتين وغابات",
    "grad_year": "2007",
    "grade": "جيد",
    "birth_date": "1984",
    "source_sheet": "مــاجستيـر"
  },
  {
    "id": 55,
    "name": "ابتسام عبدالله صالح التويتي",
    "degree": "ماجستير",
    "hiring_service": "2012-01-01",
    "hiring_univ": "2013-02-18",
    "specialization": "كيمياء فرعي فيزياء",
    "grad_year": "2004",
    "grade": "جيد",
    "birth_date": "1981",
    "source_sheet": "مــاجستيـر"
  },
  {
    "id": 56,
    "name": "افراح حمود عبدالله قيس",
    "degree": "ماجستير",
    "hiring_service": "2012-01-01",
    "hiring_univ": "2013-02-18",
    "specialization": "لغة انجليزية",
    "grad_year": "2004",
    "grade": "مقبول",
    "birth_date": "1978",
    "source_sheet": "مــاجستيـر"
  },
  {
    "id": 57,
    "name": "رجاء عبدالوهاب علي سيف",
    "degree": "ماجستير",
    "hiring_service": "2012-01-01",
    "hiring_univ": "2013-02-18",
    "specialization": "لغة انجليزية",
    "grad_year": "2004",
    "grade": "جيد",
    "birth_date": "1983",
    "source_sheet": "مــاجستيـر"
  },
  {
    "id": 58,
    "name": "سامية محمد المطري",
    "degree": "ماجستير",
    "hiring_service": "ـــــــــــــــــ",
    "hiring_univ": "2013-02-18",
    "specialization": "إذاعة وتلفزيون",
    "grad_year": "2012",
    "grade": "جيد جداً",
    "birth_date": "1980",
    "source_sheet": "مــاجستيـر"
  },
  {
    "id": 59,
    "name": "فطوم علي أحمد باسديس",
    "degree": "ماجستير",
    "hiring_service": "2012-12-01",
    "hiring_univ": "2013-02-18",
    "specialization": "دبلوم تقني",
    "grad_year": "2016",
    "grade": "جيد جداً",
    "birth_date": "1979",
    "source_sheet": "مــاجستيـر"
  },
  {
    "id": 60,
    "name": "محمد علي محمد عريش",
    "degree": "ماجستير",
    "hiring_service": "2012-01-01",
    "hiring_univ": "2013-02-18",
    "specialization": "أثار قديمة",
    "grad_year": "2019",
    "grade": "جيد",
    "birth_date": "1981",
    "source_sheet": "مــاجستيـر"
  },
  {
    "id": 61,
    "name": "جميلة صالح القطيبي",
    "degree": "ماجستير",
    "hiring_service": "ـــــــــــــــــ",
    "hiring_univ": "2013-07-28",
    "specialization": "محاسبة",
    "grad_year": "2026",
    "grade": "جيد جداً",
    "birth_date": "1985",
    "source_sheet": "مــاجستيـر"
  },
  {
    "id": 62,
    "name": "امين محمد أمين المقالح",
    "degree": "ماجستير",
    "hiring_service": "ـــــــــــــــــ",
    "hiring_univ": "2013-07-28",
    "specialization": "علوم سياسية",
    "grad_year": "2010",
    "grade": "مقبول",
    "birth_date": "1982",
    "source_sheet": "مــاجستيـر"
  },
  {
    "id": 63,
    "name": "سلوى مقبل عيظه الحداء",
    "degree": "ماجستير",
    "hiring_service": "ـــــــــــــــــ",
    "hiring_univ": "2013-10-08",
    "specialization": "لغة فرنسية",
    "grad_year": "2002",
    "grade": "جيد",
    "birth_date": "1979",
    "source_sheet": "مــاجستيـر"
  },
  {
    "id": 64,
    "name": "وليد فرحان علي راجح",
    "degree": "ماجستير",
    "hiring_service": "2016-08-14",
    "hiring_univ": "2015-09-16",
    "specialization": "إدارة عامة",
    "grad_year": "2018",
    "grade": "جيد جداً",
    "birth_date": "1983",
    "source_sheet": "مــاجستيـر"
  },
  {
    "id": 65,
    "name": "نصر محمد علي العماري",
    "degree": "ماجستير",
    "hiring_service": "2002-11-10",
    "hiring_univ": "إدارة اعمال",
    "specialization": "2009م",
    "grad_year": "جيد",
    "grade": "1979م",
    "birth_date": "",
    "source_sheet": "ماجستير مستشفى الكويت"
  },
  {
    "id": 66,
    "name": "منى علي صالح الفضلي",
    "degree": "ماجستير",
    "hiring_service": "2002-11-10",
    "hiring_univ": "تمريض",
    "specialization": "2016م",
    "grad_year": "جيد",
    "grade": "1976م",
    "birth_date": "",
    "source_sheet": "ماجستير مستشفى الكويت"
  },
  {
    "id": 67,
    "name": "معمر مهيوب سعيد قاسم",
    "degree": "ماجستير",
    "hiring_service": "2003-12-10",
    "hiring_univ": "صيدلة",
    "specialization": "2011م",
    "grad_year": "مقبول",
    "grade": "1981م",
    "birth_date": "",
    "source_sheet": "ماجستير مستشفى الكويت"
  },
  {
    "id": 68,
    "name": "ايه محمد محسن الحوثي",
    "degree": "ماجستير",
    "hiring_service": "2009-11-24",
    "hiring_univ": "إدارة اعمال",
    "specialization": "2024م",
    "grad_year": "مقبول",
    "grade": "1986م",
    "birth_date": "",
    "source_sheet": "ماجستير مستشفى الكويت"
  },
  {
    "id": 69,
    "name": "عادل عبدالقادر سيف ناجي",
    "degree": "ماجستير",
    "hiring_service": "2009-12-30",
    "hiring_univ": "طب وجراحة الفم",
    "specialization": "2010م",
    "grad_year": "جيد",
    "grade": "1980م",
    "birth_date": "",
    "source_sheet": "ماجستير مستشفى الكويت"
  },
  {
    "id": 70,
    "name": "ليبيا محمد مهيوب قائد صينا",
    "degree": "دكتوراه",
    "hiring_service": "2001-11-12",
    "hiring_univ": "هرمونات",
    "specialization": "2014م",
    "grad_year": "ـــــــــــــ",
    "grade": "1976م",
    "birth_date": "",
    "source_sheet": "دكتوراة مستشفى الكويت "
  },
  {
    "id": 71,
    "name": "محمد عبدالولي السماوي",
    "degree": "دكتوراه",
    "hiring_service": "1995م",
    "hiring_univ": "1995م",
    "specialization": "خضر",
    "grad_year": "2002",
    "grade": "ممتاز",
    "birth_date": "1970",
    "source_sheet": "كشف ملحق"
  },
  {
    "id": 72,
    "name": "أسماء محمد علي القباطي",
    "degree": "ماجستير",
    "hiring_service": "",
    "hiring_univ": "2010/12/4م",
    "specialization": "بساتين وغابات",
    "grad_year": "2008",
    "grade": "جيدجداً",
    "birth_date": "1985",
    "source_sheet": "كشف ملحق"
  },
  {
    "id": 73,
    "name": "أسماء حميد الوتاري",
    "degree": "ماجستير",
    "hiring_service": "",
    "hiring_univ": "2012-08-14",
    "specialization": "بساتين وغابات",
    "grad_year": "2010",
    "grade": "جيد",
    "birth_date": "ـــــــــــــ",
    "source_sheet": "كشف ملحق"
  },
  {
    "id": 74,
    "name": "محمد أحمد حميد",
    "degree": "ماجستير",
    "hiring_service": "",
    "hiring_univ": "2012/8/14م",
    "specialization": "هندسة زراعية",
    "grad_year": "2010",
    "grade": "جيد",
    "birth_date": "1987",
    "source_sheet": "كشف ملحق"
  },
  {
    "id": 75,
    "name": "سماح محمد صالح الجعراني",
    "degree": "ماجستير",
    "hiring_service": "",
    "hiring_univ": "2014/3/6م",
    "specialization": "بساتين وغابات",
    "grad_year": "2011",
    "grade": "جيد",
    "birth_date": "1985",
    "source_sheet": "كشف ملحق"
  },
  {
    "id": 76,
    "name": "نور عثمان كوكبة",
    "degree": "ماجستير",
    "hiring_service": "",
    "hiring_univ": "2011-07-02",
    "specialization": "علوم وتقنية غذائية",
    "grad_year": "2009",
    "grade": "جيد",
    "birth_date": "1986",
    "source_sheet": "كشف ملحق"
  }
];
